name: Is this thing even on?
on:
  workflow_run:
    workflows: [Checks]
    types:
    - completed
jobs:
  is_this_even_on:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
